---
- name: Enable MariaDB yum repository
  copy:
    src: MariaDB.repo
    dest: /etc/yum.repos.d/MariaDB.repo
    owner: root
    group: root
    mode: 0644
  become: True

- name: Import Percona GPG key
  rpm_key:
    key: 'https://yum.mariadb.org/RPM-GPG-KEY-MariaDB'
    state: present
  become: True

- name: Ensure MariaDB is installed
  yum:
    name: '{{ item }}'
    state: installed
  become: True
  with_items:
    - MariaDB-server
    - MariaDB-client
    - galera
    - rsync
    - lsof

- name: Ensure MariaDB cluster is properly configured
  template:
    src: server.cnf
    dest: /etc/my.cnf.d/server.cnf
  become: True
  notify: Restart MariaDB

- name: Ensure MariaDB can pass the firewall in the internal network
  firewalld:
    port: '{{ item }}'
    zone: internal
    state: enabled
    permanent: True
    immediate: True
  become: True
  with_items:
    - '3306/tcp'
    - '4444/tcp'
    - '4567/udp'
    - '4567/tcp'
    - '4568/tcp'

- name: Ensure MariaDB is running and enabled
  service:
    name: mysql
    state: started
    enabled: True
  become: True
